# Generated by Django 5.0.4 on 2024-08-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_disabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Taxpayer'), ('2', 'Admin1'), ('3', 'Admin2'), ('4', 'Admin3')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
