# Generated by Django 5.0.4 on 2024-08-21 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_disabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminsetting',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
