# Generated by Django 5.0.4 on 2024-08-21 20:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infra_name', models.CharField(max_length=200)),
                ('rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceid', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('length', models.IntegerField(default=0, null=True)),
                ('add_from', models.CharField(blank=True, max_length=200)),
                ('add_to', models.CharField(blank=True, max_length=200)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('year_installed', models.DateTimeField(default=datetime.datetime(2024, 8, 21, 21, 7, 42, 135032), max_length=200, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=0)),
                ('upload_application_letter', models.FileField(blank=True, null=True, upload_to='uploads/applications/')),
                ('upload_asBuilt_drawing', models.FileField(blank=True, null=True, upload_to='uploads/drawings/')),
                ('upload_payment_receipt', models.FileField(blank=True, null=True, upload_to='uploads/receipts/')),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed'), ('Revised', 'Revised')], default='UNPAID', max_length=10)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('is_disputed', models.BooleanField(default=False)),
                ('is_undisputed', models.BooleanField(default=False)),
                ('is_revised', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_existing', models.BooleanField(default=False)),
                ('infra_cost', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
                ('infra_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra_type', to='tax.infrastructuretype')),
            ],
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceid', models.CharField(max_length=200)),
                ('remitted_amount', models.IntegerField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='uploads/receipts/')),
                ('approved', models.BooleanField(default=False)),
                ('apply_for_waver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remit_comp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Waver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceid', models.CharField(max_length=200)),
                ('wave_amount', models.IntegerField(default=0)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='uploads/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
