# Generated by Django 5.0.4 on 2024-08-21 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 21, 26, 47, 88035), max_length=200, null=True),
        ),
    ]
