# Generated by Django 5.0.4 on 2024-08-21 22:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_alter_permit_year_installed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='infrastructuretype',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='remittance',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='permit',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permit',
            name='infra_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra', to='tax.infrastructuretype'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 23, 34, 14, 203451), max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('year_installed', models.DateTimeField(default=datetime.datetime(2024, 8, 21, 23, 34, 14, 200450), max_length=200, null=True)),
                ('upload_application_letter', models.FileField(blank=True, null=True, upload_to='uploads/applications/')),
                ('upload_asBuilt_drawing', models.FileField(blank=True, null=True, upload_to='uploads/drawings/')),
                ('is_existing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com', to=settings.AUTH_USER_MODEL)),
                ('infra_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra_type', to='tax.infrastructuretype')),
            ],
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceid', models.CharField(max_length=200)),
                ('wave_amount', models.IntegerField(default=0)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='uploads/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceid', models.CharField(max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed'), ('Revised', 'Revised')], default='UNPAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
                ('remittance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittance', to='tax.remittance')),
                ('waiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiver', to='tax.waiver')),
            ],
        ),
        migrations.DeleteModel(
            name='Waver',
        ),
    ]
