# Generated by Django 5.0.4 on 2024-08-21 22:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_rename_modified_at_infrastructuretype_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandnotice',
            name='remittance',
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 23, 39, 32, 704499), max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 23, 39, 32, 706498), max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='referenceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refid', to='tax.demandnotice'),
        ),
    ]
