# Generated by Django 5.0.4 on 2024-08-21 22:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0006_remove_demandnotice_remittance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandnotice',
            name='waiver',
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 23, 42, 59, 821529), max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 23, 42, 59, 824528), max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='referenceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittance', to='tax.demandnotice'),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='referenceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver', to='tax.demandnotice'),
        ),
    ]
