# Generated by Django 5.0.4 on 2024-08-21 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0007_remove_demandnotice_waiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='year_installed',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 23, 48, 44, 845565), max_length=200, null=True),
        ),
    ]
