# Generated by Django 5.0.4 on 2024-08-24 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0008_alter_infrastructure_year_installed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 24, 1, 20, 48, 343423), max_length=200, null=True),
        ),
    ]
