# Generated by Django 5.0.4 on 2024-08-27 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0009_infrastructure_cost_alter_permit_year_installed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandnotice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('DISPUTED', 'Disputed'), ('REVISED', 'Revised'), ('PAID', 'Paid'), ('RESOLVED', 'Resolved')], default='UNPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 9, 59, 53, 633975), max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='referenceid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='referenceid',
            field=models.CharField(max_length=20),
        ),
    ]
