# Generated by Django 5.0.4 on 2024-08-29 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0010_alter_demandnotice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 29, 23, 5, 49, 193892), max_length=200, null=True),
        ),
    ]
