# Generated by Django 5.0.4 on 2024-08-30 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0012_demandnotice_is_exisiting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='refernceid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 20, 20, 3, 43369), max_length=200, null=True),
        ),
    ]
