# Generated by Django 5.0.4 on 2024-08-30 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0013_infrastructure_refernceid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infrastructure',
            old_name='refernceid',
            new_name='referenceid',
        ),
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 20, 26, 48, 261997), max_length=200, null=True),
        ),
    ]
