# Generated by Django 5.0.4 on 2024-08-30 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0014_rename_refernceid_infrastructure_referenceid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandnotice',
            name='admin_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandnotice',
            name='application_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandnotice',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandnotice',
            name='infra',
            field=models.CharField(default=[], max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandnotice',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandnotice',
            name='penalty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandnotice',
            name='site_assessment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandnotice',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandnotice',
            name='total_due',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 21, 29, 31, 65073), max_length=200, null=True),
        ),
    ]
