# Generated by Django 5.0.4 on 2024-08-31 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0015_demandnotice_admin_fee_demandnotice_application_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandnotice',
            name='remittance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandnotice',
            name='waiver',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='demandnotice',
            name='infra',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 16, 52, 32, 221635), max_length=200, null=True),
        ),
    ]
