# Generated by Django 5.0.4 on 2024-09-02 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0016_demandnotice_remittance_demandnotice_waiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandnotice',
            old_name='paid_amount',
            new_name='amount_due',
        ),
        migrations.RenameField(
            model_name='demandnotice',
            old_name='waiver',
            new_name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='demandnotice',
            name='balance',
        ),
        migrations.AddField(
            model_name='demandnotice',
            name='waiver_applied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='demandnotice',
            name='status',
            field=models.CharField(choices=[('DEMAND NOTICE', 'Demand Notice'), ('UNDISPUTED', 'Undisputed'), ('UNDISPUTED PAID', 'Undisputed Paid'), ('REVISED', 'Revised'), ('RESOLVED', 'Resolved')], default='UNPAID', max_length=30),
        ),
        migrations.AlterField(
            model_name='demandnotice',
            name='total_due',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 34, 44, 285649), max_length=200, null=True),
        ),
    ]
