# Generated by Django 5.0.4 on 2024-09-10 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0018_demandnotice_annual_fee_alter_demandnotice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 9, 48, 49, 598354), max_length=200, null=True),
        ),
    ]
