# Generated by Django 5.0.4 on 2024-09-10 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0019_alter_permit_year_installed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 9, 55, 7, 193839), max_length=200, null=True),
        ),
    ]
