# Generated by Django 5.0.4 on 2024-09-10 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0020_alter_permit_year_installed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 10, 3, 54, 841864), max_length=200, null=True),
        ),
    ]
