# Generated by Django 5.0.4 on 2024-09-13 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0023_alter_permit_year_installed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandnotice',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 9, 19, 18, 489647), max_length=200, null=True),
        ),
    ]
