# Generated by Django 5.0.4 on 2024-09-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0026_historicaldemandnotice_historicalinfrastructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinfrastructure',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalinfrastructure',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinfrastructure',
            name='infra_type',
        ),
        migrations.DeleteModel(
            name='HistoricalDemandNotice',
        ),
        migrations.DeleteModel(
            name='HistoricalInfrastructure',
        ),
    ]
