# Generated by Django 5.0.4 on 2024-08-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
